require 'paperclip'
require 'secure_attachment/paperclip/media_spoof_detector'
require 'secure_attachment/registry'
require 'secure_attachment/has_secure_attached_file'
require 'secure_attachment/secure_paperclip_extn'
